num_threads = 4
root = 'D:\Code\'
out_dir = 'D:\Code\out'

global_includes = ["**/*.cs", "**/*.h"]
global_excludes = ['*/Code/*']

[[patches]]
preprocessor = "InnerRemover"
preprocessor_params = ["InnerRemover", "(", ")"]
find = "a"
replace = "b"